package cn.coderss.service.user.model;

public class CmsCommentmeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_commentmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long metaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_commentmeta.comment_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_commentmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_commentmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_commentmeta.meta_id
     *
     * @return the value of cms_commentmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getMetaId() {
        return metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_commentmeta.meta_id
     *
     * @param metaId the value for cms_commentmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_commentmeta.comment_id
     *
     * @return the value of cms_commentmeta.comment_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_commentmeta.comment_id
     *
     * @param commentId the value for cms_commentmeta.comment_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_commentmeta.meta_key
     *
     * @return the value of cms_commentmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_commentmeta.meta_key
     *
     * @param metaKey the value for cms_commentmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_commentmeta.meta_value
     *
     * @return the value of cms_commentmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaValue() {
        return metaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_commentmeta.meta_value
     *
     * @param metaValue the value for cms_commentmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }
}