package cn.coderss.service.user.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CmsCommentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public CmsCommentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_ID is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Long value) {
            addCriterion("comment_ID =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Long value) {
            addCriterion("comment_ID <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Long value) {
            addCriterion("comment_ID >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_ID >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Long value) {
            addCriterion("comment_ID <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Long value) {
            addCriterion("comment_ID <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Long> values) {
            addCriterion("comment_ID in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Long> values) {
            addCriterion("comment_ID not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Long value1, Long value2) {
            addCriterion("comment_ID between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Long value1, Long value2) {
            addCriterion("comment_ID not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdIsNull() {
            addCriterion("comment_post_ID is null");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdIsNotNull() {
            addCriterion("comment_post_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdEqualTo(Long value) {
            addCriterion("comment_post_ID =", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdNotEqualTo(Long value) {
            addCriterion("comment_post_ID <>", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdGreaterThan(Long value) {
            addCriterion("comment_post_ID >", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_post_ID >=", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdLessThan(Long value) {
            addCriterion("comment_post_ID <", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdLessThanOrEqualTo(Long value) {
            addCriterion("comment_post_ID <=", value, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdIn(List<Long> values) {
            addCriterion("comment_post_ID in", values, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdNotIn(List<Long> values) {
            addCriterion("comment_post_ID not in", values, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdBetween(Long value1, Long value2) {
            addCriterion("comment_post_ID between", value1, value2, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentPostIdNotBetween(Long value1, Long value2) {
            addCriterion("comment_post_ID not between", value1, value2, "commentPostId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIsNull() {
            addCriterion("comment_author is null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIsNotNull() {
            addCriterion("comment_author is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEqualTo(String value) {
            addCriterion("comment_author =", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorNotEqualTo(String value) {
            addCriterion("comment_author <>", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorGreaterThan(String value) {
            addCriterion("comment_author >", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("comment_author >=", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorLessThan(String value) {
            addCriterion("comment_author <", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorLessThanOrEqualTo(String value) {
            addCriterion("comment_author <=", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorLike(String value) {
            addCriterion("comment_author like", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorNotLike(String value) {
            addCriterion("comment_author not like", value, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIn(List<String> values) {
            addCriterion("comment_author in", values, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorNotIn(List<String> values) {
            addCriterion("comment_author not in", values, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorBetween(String value1, String value2) {
            addCriterion("comment_author between", value1, value2, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorNotBetween(String value1, String value2) {
            addCriterion("comment_author not between", value1, value2, "commentAuthor");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailIsNull() {
            addCriterion("comment_author_email is null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailIsNotNull() {
            addCriterion("comment_author_email is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailEqualTo(String value) {
            addCriterion("comment_author_email =", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailNotEqualTo(String value) {
            addCriterion("comment_author_email <>", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailGreaterThan(String value) {
            addCriterion("comment_author_email >", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailGreaterThanOrEqualTo(String value) {
            addCriterion("comment_author_email >=", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailLessThan(String value) {
            addCriterion("comment_author_email <", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailLessThanOrEqualTo(String value) {
            addCriterion("comment_author_email <=", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailLike(String value) {
            addCriterion("comment_author_email like", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailNotLike(String value) {
            addCriterion("comment_author_email not like", value, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailIn(List<String> values) {
            addCriterion("comment_author_email in", values, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailNotIn(List<String> values) {
            addCriterion("comment_author_email not in", values, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailBetween(String value1, String value2) {
            addCriterion("comment_author_email between", value1, value2, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorEmailNotBetween(String value1, String value2) {
            addCriterion("comment_author_email not between", value1, value2, "commentAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlIsNull() {
            addCriterion("comment_author_url is null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlIsNotNull() {
            addCriterion("comment_author_url is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlEqualTo(String value) {
            addCriterion("comment_author_url =", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlNotEqualTo(String value) {
            addCriterion("comment_author_url <>", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlGreaterThan(String value) {
            addCriterion("comment_author_url >", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlGreaterThanOrEqualTo(String value) {
            addCriterion("comment_author_url >=", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlLessThan(String value) {
            addCriterion("comment_author_url <", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlLessThanOrEqualTo(String value) {
            addCriterion("comment_author_url <=", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlLike(String value) {
            addCriterion("comment_author_url like", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlNotLike(String value) {
            addCriterion("comment_author_url not like", value, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlIn(List<String> values) {
            addCriterion("comment_author_url in", values, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlNotIn(List<String> values) {
            addCriterion("comment_author_url not in", values, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlBetween(String value1, String value2) {
            addCriterion("comment_author_url between", value1, value2, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorUrlNotBetween(String value1, String value2) {
            addCriterion("comment_author_url not between", value1, value2, "commentAuthorUrl");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpIsNull() {
            addCriterion("comment_author_IP is null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpIsNotNull() {
            addCriterion("comment_author_IP is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpEqualTo(String value) {
            addCriterion("comment_author_IP =", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpNotEqualTo(String value) {
            addCriterion("comment_author_IP <>", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpGreaterThan(String value) {
            addCriterion("comment_author_IP >", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpGreaterThanOrEqualTo(String value) {
            addCriterion("comment_author_IP >=", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpLessThan(String value) {
            addCriterion("comment_author_IP <", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpLessThanOrEqualTo(String value) {
            addCriterion("comment_author_IP <=", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpLike(String value) {
            addCriterion("comment_author_IP like", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpNotLike(String value) {
            addCriterion("comment_author_IP not like", value, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpIn(List<String> values) {
            addCriterion("comment_author_IP in", values, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpNotIn(List<String> values) {
            addCriterion("comment_author_IP not in", values, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpBetween(String value1, String value2) {
            addCriterion("comment_author_IP between", value1, value2, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIpNotBetween(String value1, String value2) {
            addCriterion("comment_author_IP not between", value1, value2, "commentAuthorIp");
            return (Criteria) this;
        }

        public Criteria andCommentDateIsNull() {
            addCriterion("comment_date is null");
            return (Criteria) this;
        }

        public Criteria andCommentDateIsNotNull() {
            addCriterion("comment_date is not null");
            return (Criteria) this;
        }

        public Criteria andCommentDateEqualTo(Date value) {
            addCriterion("comment_date =", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateNotEqualTo(Date value) {
            addCriterion("comment_date <>", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateGreaterThan(Date value) {
            addCriterion("comment_date >", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateGreaterThanOrEqualTo(Date value) {
            addCriterion("comment_date >=", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateLessThan(Date value) {
            addCriterion("comment_date <", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateLessThanOrEqualTo(Date value) {
            addCriterion("comment_date <=", value, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateIn(List<Date> values) {
            addCriterion("comment_date in", values, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateNotIn(List<Date> values) {
            addCriterion("comment_date not in", values, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateBetween(Date value1, Date value2) {
            addCriterion("comment_date between", value1, value2, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateNotBetween(Date value1, Date value2) {
            addCriterion("comment_date not between", value1, value2, "commentDate");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtIsNull() {
            addCriterion("comment_date_gmt is null");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtIsNotNull() {
            addCriterion("comment_date_gmt is not null");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtEqualTo(Date value) {
            addCriterion("comment_date_gmt =", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtNotEqualTo(Date value) {
            addCriterion("comment_date_gmt <>", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtGreaterThan(Date value) {
            addCriterion("comment_date_gmt >", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtGreaterThanOrEqualTo(Date value) {
            addCriterion("comment_date_gmt >=", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtLessThan(Date value) {
            addCriterion("comment_date_gmt <", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtLessThanOrEqualTo(Date value) {
            addCriterion("comment_date_gmt <=", value, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtIn(List<Date> values) {
            addCriterion("comment_date_gmt in", values, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtNotIn(List<Date> values) {
            addCriterion("comment_date_gmt not in", values, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtBetween(Date value1, Date value2) {
            addCriterion("comment_date_gmt between", value1, value2, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentDateGmtNotBetween(Date value1, Date value2) {
            addCriterion("comment_date_gmt not between", value1, value2, "commentDateGmt");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaIsNull() {
            addCriterion("comment_karma is null");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaIsNotNull() {
            addCriterion("comment_karma is not null");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaEqualTo(Integer value) {
            addCriterion("comment_karma =", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaNotEqualTo(Integer value) {
            addCriterion("comment_karma <>", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaGreaterThan(Integer value) {
            addCriterion("comment_karma >", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_karma >=", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaLessThan(Integer value) {
            addCriterion("comment_karma <", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaLessThanOrEqualTo(Integer value) {
            addCriterion("comment_karma <=", value, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaIn(List<Integer> values) {
            addCriterion("comment_karma in", values, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaNotIn(List<Integer> values) {
            addCriterion("comment_karma not in", values, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaBetween(Integer value1, Integer value2) {
            addCriterion("comment_karma between", value1, value2, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentKarmaNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_karma not between", value1, value2, "commentKarma");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedIsNull() {
            addCriterion("comment_approved is null");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedIsNotNull() {
            addCriterion("comment_approved is not null");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedEqualTo(String value) {
            addCriterion("comment_approved =", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedNotEqualTo(String value) {
            addCriterion("comment_approved <>", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedGreaterThan(String value) {
            addCriterion("comment_approved >", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedGreaterThanOrEqualTo(String value) {
            addCriterion("comment_approved >=", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedLessThan(String value) {
            addCriterion("comment_approved <", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedLessThanOrEqualTo(String value) {
            addCriterion("comment_approved <=", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedLike(String value) {
            addCriterion("comment_approved like", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedNotLike(String value) {
            addCriterion("comment_approved not like", value, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedIn(List<String> values) {
            addCriterion("comment_approved in", values, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedNotIn(List<String> values) {
            addCriterion("comment_approved not in", values, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedBetween(String value1, String value2) {
            addCriterion("comment_approved between", value1, value2, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentApprovedNotBetween(String value1, String value2) {
            addCriterion("comment_approved not between", value1, value2, "commentApproved");
            return (Criteria) this;
        }

        public Criteria andCommentAgentIsNull() {
            addCriterion("comment_agent is null");
            return (Criteria) this;
        }

        public Criteria andCommentAgentIsNotNull() {
            addCriterion("comment_agent is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAgentEqualTo(String value) {
            addCriterion("comment_agent =", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentNotEqualTo(String value) {
            addCriterion("comment_agent <>", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentGreaterThan(String value) {
            addCriterion("comment_agent >", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentGreaterThanOrEqualTo(String value) {
            addCriterion("comment_agent >=", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentLessThan(String value) {
            addCriterion("comment_agent <", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentLessThanOrEqualTo(String value) {
            addCriterion("comment_agent <=", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentLike(String value) {
            addCriterion("comment_agent like", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentNotLike(String value) {
            addCriterion("comment_agent not like", value, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentIn(List<String> values) {
            addCriterion("comment_agent in", values, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentNotIn(List<String> values) {
            addCriterion("comment_agent not in", values, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentBetween(String value1, String value2) {
            addCriterion("comment_agent between", value1, value2, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentAgentNotBetween(String value1, String value2) {
            addCriterion("comment_agent not between", value1, value2, "commentAgent");
            return (Criteria) this;
        }

        public Criteria andCommentTypeIsNull() {
            addCriterion("comment_type is null");
            return (Criteria) this;
        }

        public Criteria andCommentTypeIsNotNull() {
            addCriterion("comment_type is not null");
            return (Criteria) this;
        }

        public Criteria andCommentTypeEqualTo(String value) {
            addCriterion("comment_type =", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeNotEqualTo(String value) {
            addCriterion("comment_type <>", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeGreaterThan(String value) {
            addCriterion("comment_type >", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("comment_type >=", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeLessThan(String value) {
            addCriterion("comment_type <", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeLessThanOrEqualTo(String value) {
            addCriterion("comment_type <=", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeLike(String value) {
            addCriterion("comment_type like", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeNotLike(String value) {
            addCriterion("comment_type not like", value, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeIn(List<String> values) {
            addCriterion("comment_type in", values, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeNotIn(List<String> values) {
            addCriterion("comment_type not in", values, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeBetween(String value1, String value2) {
            addCriterion("comment_type between", value1, value2, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentTypeNotBetween(String value1, String value2) {
            addCriterion("comment_type not between", value1, value2, "commentType");
            return (Criteria) this;
        }

        public Criteria andCommentParentIsNull() {
            addCriterion("comment_parent is null");
            return (Criteria) this;
        }

        public Criteria andCommentParentIsNotNull() {
            addCriterion("comment_parent is not null");
            return (Criteria) this;
        }

        public Criteria andCommentParentEqualTo(Long value) {
            addCriterion("comment_parent =", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentNotEqualTo(Long value) {
            addCriterion("comment_parent <>", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentGreaterThan(Long value) {
            addCriterion("comment_parent >", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_parent >=", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentLessThan(Long value) {
            addCriterion("comment_parent <", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentLessThanOrEqualTo(Long value) {
            addCriterion("comment_parent <=", value, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentIn(List<Long> values) {
            addCriterion("comment_parent in", values, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentNotIn(List<Long> values) {
            addCriterion("comment_parent not in", values, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentBetween(Long value1, Long value2) {
            addCriterion("comment_parent between", value1, value2, "commentParent");
            return (Criteria) this;
        }

        public Criteria andCommentParentNotBetween(Long value1, Long value2) {
            addCriterion("comment_parent not between", value1, value2, "commentParent");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_comments
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 02 09:25:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_comments
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}