package cn.coderss.service.user.model;

import java.util.Date;

public class CmsComments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_post_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long commentPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_author_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentAuthorEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_author_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentAuthorUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_author_IP
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentAuthorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date commentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date commentDateGmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_karma
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Integer commentKarma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_approved
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentApproved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_agent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long commentParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.user_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comments.comment_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_ID
     *
     * @return the value of cms_comments.comment_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_ID
     *
     * @param commentId the value for cms_comments.comment_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_post_ID
     *
     * @return the value of cms_comments.comment_post_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCommentPostId() {
        return commentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_post_ID
     *
     * @param commentPostId the value for cms_comments.comment_post_ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentPostId(Long commentPostId) {
        this.commentPostId = commentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_author
     *
     * @return the value of cms_comments.comment_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentAuthor() {
        return commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_author
     *
     * @param commentAuthor the value for cms_comments.comment_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_author_email
     *
     * @return the value of cms_comments.comment_author_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentAuthorEmail() {
        return commentAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_author_email
     *
     * @param commentAuthorEmail the value for cms_comments.comment_author_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentAuthorEmail(String commentAuthorEmail) {
        this.commentAuthorEmail = commentAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_author_url
     *
     * @return the value of cms_comments.comment_author_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentAuthorUrl() {
        return commentAuthorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_author_url
     *
     * @param commentAuthorUrl the value for cms_comments.comment_author_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentAuthorUrl(String commentAuthorUrl) {
        this.commentAuthorUrl = commentAuthorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_author_IP
     *
     * @return the value of cms_comments.comment_author_IP
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentAuthorIp() {
        return commentAuthorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_author_IP
     *
     * @param commentAuthorIp the value for cms_comments.comment_author_IP
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentAuthorIp(String commentAuthorIp) {
        this.commentAuthorIp = commentAuthorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_date
     *
     * @return the value of cms_comments.comment_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_date
     *
     * @param commentDate the value for cms_comments.comment_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_date_gmt
     *
     * @return the value of cms_comments.comment_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getCommentDateGmt() {
        return commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_date_gmt
     *
     * @param commentDateGmt the value for cms_comments.comment_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentDateGmt(Date commentDateGmt) {
        this.commentDateGmt = commentDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_karma
     *
     * @return the value of cms_comments.comment_karma
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Integer getCommentKarma() {
        return commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_karma
     *
     * @param commentKarma the value for cms_comments.comment_karma
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentKarma(Integer commentKarma) {
        this.commentKarma = commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_approved
     *
     * @return the value of cms_comments.comment_approved
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentApproved() {
        return commentApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_approved
     *
     * @param commentApproved the value for cms_comments.comment_approved
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentApproved(String commentApproved) {
        this.commentApproved = commentApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_agent
     *
     * @return the value of cms_comments.comment_agent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentAgent() {
        return commentAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_agent
     *
     * @param commentAgent the value for cms_comments.comment_agent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_type
     *
     * @return the value of cms_comments.comment_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_type
     *
     * @param commentType the value for cms_comments.comment_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentType(String commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_parent
     *
     * @return the value of cms_comments.comment_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCommentParent() {
        return commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_parent
     *
     * @param commentParent the value for cms_comments.comment_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentParent(Long commentParent) {
        this.commentParent = commentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.user_id
     *
     * @return the value of cms_comments.user_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.user_id
     *
     * @param userId the value for cms_comments.user_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comments.comment_content
     *
     * @return the value of cms_comments.comment_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comments.comment_content
     *
     * @param commentContent the value for cms_comments.comment_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
}