package cn.coderss.service.user.model;

import java.util.Date;

public class CmsLinks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_image
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_target
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_visible
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkVisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_owner
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long linkOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_rating
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Integer linkRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_updated
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date linkUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_rel
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkRel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_rss
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkRss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_links.link_notes
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String linkNotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_id
     *
     * @return the value of cms_links.link_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_id
     *
     * @param linkId the value for cms_links.link_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkId(Long linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_url
     *
     * @return the value of cms_links.link_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_url
     *
     * @param linkUrl the value for cms_links.link_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_name
     *
     * @return the value of cms_links.link_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_name
     *
     * @param linkName the value for cms_links.link_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_image
     *
     * @return the value of cms_links.link_image
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkImage() {
        return linkImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_image
     *
     * @param linkImage the value for cms_links.link_image
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkImage(String linkImage) {
        this.linkImage = linkImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_target
     *
     * @return the value of cms_links.link_target
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkTarget() {
        return linkTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_target
     *
     * @param linkTarget the value for cms_links.link_target
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkTarget(String linkTarget) {
        this.linkTarget = linkTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_description
     *
     * @return the value of cms_links.link_description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkDescription() {
        return linkDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_description
     *
     * @param linkDescription the value for cms_links.link_description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkDescription(String linkDescription) {
        this.linkDescription = linkDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_visible
     *
     * @return the value of cms_links.link_visible
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkVisible() {
        return linkVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_visible
     *
     * @param linkVisible the value for cms_links.link_visible
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkVisible(String linkVisible) {
        this.linkVisible = linkVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_owner
     *
     * @return the value of cms_links.link_owner
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getLinkOwner() {
        return linkOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_owner
     *
     * @param linkOwner the value for cms_links.link_owner
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkOwner(Long linkOwner) {
        this.linkOwner = linkOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_rating
     *
     * @return the value of cms_links.link_rating
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Integer getLinkRating() {
        return linkRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_rating
     *
     * @param linkRating the value for cms_links.link_rating
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkRating(Integer linkRating) {
        this.linkRating = linkRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_updated
     *
     * @return the value of cms_links.link_updated
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getLinkUpdated() {
        return linkUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_updated
     *
     * @param linkUpdated the value for cms_links.link_updated
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkUpdated(Date linkUpdated) {
        this.linkUpdated = linkUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_rel
     *
     * @return the value of cms_links.link_rel
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkRel() {
        return linkRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_rel
     *
     * @param linkRel the value for cms_links.link_rel
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkRel(String linkRel) {
        this.linkRel = linkRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_rss
     *
     * @return the value of cms_links.link_rss
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkRss() {
        return linkRss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_rss
     *
     * @param linkRss the value for cms_links.link_rss
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkRss(String linkRss) {
        this.linkRss = linkRss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_links.link_notes
     *
     * @return the value of cms_links.link_notes
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getLinkNotes() {
        return linkNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_links.link_notes
     *
     * @param linkNotes the value for cms_links.link_notes
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setLinkNotes(String linkNotes) {
        this.linkNotes = linkNotes;
    }
}