package cn.coderss.service.user.model;

public class CmsOptions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_options.option_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_options.option_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_options.autoload
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String autoload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_options.option_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String optionValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_options.option_id
     *
     * @return the value of cms_options.option_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_options.option_id
     *
     * @param optionId the value for cms_options.option_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_options.option_name
     *
     * @return the value of cms_options.option_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_options.option_name
     *
     * @param optionName the value for cms_options.option_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_options.autoload
     *
     * @return the value of cms_options.autoload
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getAutoload() {
        return autoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_options.autoload
     *
     * @param autoload the value for cms_options.autoload
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setAutoload(String autoload) {
        this.autoload = autoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_options.option_value
     *
     * @return the value of cms_options.option_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_options.option_value
     *
     * @param optionValue the value for cms_options.option_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
}