package cn.coderss.service.user.model;

import java.util.Date;

public class CmsPosts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long postAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date postDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date postDateGmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.comment_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.ping_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String pingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_password
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_modified
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date postModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_modified_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date postModifiedGmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long postParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.guid
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.menu_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_mime_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postMimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.comment_count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_title
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_excerpt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postExcerpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.to_ping
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String toPing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.pinged
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String pinged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_posts.post_content_filtered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String postContentFiltered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.ID
     *
     * @return the value of cms_posts.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.ID
     *
     * @param id the value for cms_posts.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_author
     *
     * @return the value of cms_posts.post_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getPostAuthor() {
        return postAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_author
     *
     * @param postAuthor the value for cms_posts.post_author
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostAuthor(Long postAuthor) {
        this.postAuthor = postAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_date
     *
     * @return the value of cms_posts.post_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_date
     *
     * @param postDate the value for cms_posts.post_date
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_date_gmt
     *
     * @return the value of cms_posts.post_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getPostDateGmt() {
        return postDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_date_gmt
     *
     * @param postDateGmt the value for cms_posts.post_date_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostDateGmt(Date postDateGmt) {
        this.postDateGmt = postDateGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_status
     *
     * @return the value of cms_posts.post_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_status
     *
     * @param postStatus the value for cms_posts.post_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostStatus(String postStatus) {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.comment_status
     *
     * @return the value of cms_posts.comment_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.comment_status
     *
     * @param commentStatus the value for cms_posts.comment_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.ping_status
     *
     * @return the value of cms_posts.ping_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPingStatus() {
        return pingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.ping_status
     *
     * @param pingStatus the value for cms_posts.ping_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPingStatus(String pingStatus) {
        this.pingStatus = pingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_password
     *
     * @return the value of cms_posts.post_password
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostPassword() {
        return postPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_password
     *
     * @param postPassword the value for cms_posts.post_password
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostPassword(String postPassword) {
        this.postPassword = postPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_name
     *
     * @return the value of cms_posts.post_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_name
     *
     * @param postName the value for cms_posts.post_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_modified
     *
     * @return the value of cms_posts.post_modified
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getPostModified() {
        return postModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_modified
     *
     * @param postModified the value for cms_posts.post_modified
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostModified(Date postModified) {
        this.postModified = postModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_modified_gmt
     *
     * @return the value of cms_posts.post_modified_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getPostModifiedGmt() {
        return postModifiedGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_modified_gmt
     *
     * @param postModifiedGmt the value for cms_posts.post_modified_gmt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostModifiedGmt(Date postModifiedGmt) {
        this.postModifiedGmt = postModifiedGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_parent
     *
     * @return the value of cms_posts.post_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getPostParent() {
        return postParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_parent
     *
     * @param postParent the value for cms_posts.post_parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostParent(Long postParent) {
        this.postParent = postParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.guid
     *
     * @return the value of cms_posts.guid
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.guid
     *
     * @param guid the value for cms_posts.guid
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.menu_order
     *
     * @return the value of cms_posts.menu_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.menu_order
     *
     * @param menuOrder the value for cms_posts.menu_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_type
     *
     * @return the value of cms_posts.post_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_type
     *
     * @param postType the value for cms_posts.post_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostType(String postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_mime_type
     *
     * @return the value of cms_posts.post_mime_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostMimeType() {
        return postMimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_mime_type
     *
     * @param postMimeType the value for cms_posts.post_mime_type
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostMimeType(String postMimeType) {
        this.postMimeType = postMimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.comment_count
     *
     * @return the value of cms_posts.comment_count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.comment_count
     *
     * @param commentCount the value for cms_posts.comment_count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_content
     *
     * @return the value of cms_posts.post_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_content
     *
     * @param postContent the value for cms_posts.post_content
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_title
     *
     * @return the value of cms_posts.post_title
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_title
     *
     * @param postTitle the value for cms_posts.post_title
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_excerpt
     *
     * @return the value of cms_posts.post_excerpt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostExcerpt() {
        return postExcerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_excerpt
     *
     * @param postExcerpt the value for cms_posts.post_excerpt
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostExcerpt(String postExcerpt) {
        this.postExcerpt = postExcerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.to_ping
     *
     * @return the value of cms_posts.to_ping
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getToPing() {
        return toPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.to_ping
     *
     * @param toPing the value for cms_posts.to_ping
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setToPing(String toPing) {
        this.toPing = toPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.pinged
     *
     * @return the value of cms_posts.pinged
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPinged() {
        return pinged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.pinged
     *
     * @param pinged the value for cms_posts.pinged
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPinged(String pinged) {
        this.pinged = pinged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_posts.post_content_filtered
     *
     * @return the value of cms_posts.post_content_filtered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getPostContentFiltered() {
        return postContentFiltered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_posts.post_content_filtered
     *
     * @param postContentFiltered the value for cms_posts.post_content_filtered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostContentFiltered(String postContentFiltered) {
        this.postContentFiltered = postContentFiltered;
    }
}