package cn.coderss.service.user.model;

public class CmsPostmeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_postmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long metaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_postmeta.post_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_postmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_postmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_postmeta.meta_id
     *
     * @return the value of cms_postmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getMetaId() {
        return metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_postmeta.meta_id
     *
     * @param metaId the value for cms_postmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_postmeta.post_id
     *
     * @return the value of cms_postmeta.post_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_postmeta.post_id
     *
     * @param postId the value for cms_postmeta.post_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_postmeta.meta_key
     *
     * @return the value of cms_postmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_postmeta.meta_key
     *
     * @param metaKey the value for cms_postmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_postmeta.meta_value
     *
     * @return the value of cms_postmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaValue() {
        return metaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_postmeta.meta_value
     *
     * @param metaValue the value for cms_postmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }
}