package cn.coderss.service.user.model;

import java.util.ArrayList;
import java.util.List;

public class CmsTermmetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public CmsTermmetaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMetaIdIsNull() {
            addCriterion("meta_id is null");
            return (Criteria) this;
        }

        public Criteria andMetaIdIsNotNull() {
            addCriterion("meta_id is not null");
            return (Criteria) this;
        }

        public Criteria andMetaIdEqualTo(Long value) {
            addCriterion("meta_id =", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdNotEqualTo(Long value) {
            addCriterion("meta_id <>", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdGreaterThan(Long value) {
            addCriterion("meta_id >", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("meta_id >=", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdLessThan(Long value) {
            addCriterion("meta_id <", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdLessThanOrEqualTo(Long value) {
            addCriterion("meta_id <=", value, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdIn(List<Long> values) {
            addCriterion("meta_id in", values, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdNotIn(List<Long> values) {
            addCriterion("meta_id not in", values, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdBetween(Long value1, Long value2) {
            addCriterion("meta_id between", value1, value2, "metaId");
            return (Criteria) this;
        }

        public Criteria andMetaIdNotBetween(Long value1, Long value2) {
            addCriterion("meta_id not between", value1, value2, "metaId");
            return (Criteria) this;
        }

        public Criteria andTermIdIsNull() {
            addCriterion("term_id is null");
            return (Criteria) this;
        }

        public Criteria andTermIdIsNotNull() {
            addCriterion("term_id is not null");
            return (Criteria) this;
        }

        public Criteria andTermIdEqualTo(Long value) {
            addCriterion("term_id =", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotEqualTo(Long value) {
            addCriterion("term_id <>", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThan(Long value) {
            addCriterion("term_id >", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThanOrEqualTo(Long value) {
            addCriterion("term_id >=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThan(Long value) {
            addCriterion("term_id <", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThanOrEqualTo(Long value) {
            addCriterion("term_id <=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdIn(List<Long> values) {
            addCriterion("term_id in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotIn(List<Long> values) {
            addCriterion("term_id not in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdBetween(Long value1, Long value2) {
            addCriterion("term_id between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotBetween(Long value1, Long value2) {
            addCriterion("term_id not between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andMetaKeyIsNull() {
            addCriterion("meta_key is null");
            return (Criteria) this;
        }

        public Criteria andMetaKeyIsNotNull() {
            addCriterion("meta_key is not null");
            return (Criteria) this;
        }

        public Criteria andMetaKeyEqualTo(String value) {
            addCriterion("meta_key =", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyNotEqualTo(String value) {
            addCriterion("meta_key <>", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyGreaterThan(String value) {
            addCriterion("meta_key >", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyGreaterThanOrEqualTo(String value) {
            addCriterion("meta_key >=", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyLessThan(String value) {
            addCriterion("meta_key <", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyLessThanOrEqualTo(String value) {
            addCriterion("meta_key <=", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyLike(String value) {
            addCriterion("meta_key like", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyNotLike(String value) {
            addCriterion("meta_key not like", value, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyIn(List<String> values) {
            addCriterion("meta_key in", values, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyNotIn(List<String> values) {
            addCriterion("meta_key not in", values, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyBetween(String value1, String value2) {
            addCriterion("meta_key between", value1, value2, "metaKey");
            return (Criteria) this;
        }

        public Criteria andMetaKeyNotBetween(String value1, String value2) {
            addCriterion("meta_key not between", value1, value2, "metaKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_termmeta
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 02 09:25:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}