package cn.coderss.service.user.model;

public class CmsTermRelationships {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_relationships.object_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_relationships.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termTaxonomyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_relationships.term_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Integer termOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_relationships.object_id
     *
     * @return the value of cms_term_relationships.object_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_relationships.object_id
     *
     * @param objectId the value for cms_term_relationships.object_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_relationships.term_taxonomy_id
     *
     * @return the value of cms_term_relationships.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_relationships.term_taxonomy_id
     *
     * @param termTaxonomyId the value for cms_term_relationships.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_relationships.term_order
     *
     * @return the value of cms_term_relationships.term_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Integer getTermOrder() {
        return termOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_relationships.term_order
     *
     * @param termOrder the value for cms_term_relationships.term_order
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermOrder(Integer termOrder) {
        this.termOrder = termOrder;
    }
}