package cn.coderss.service.user.model;

public class CmsTermTaxonomy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termTaxonomyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String taxonomy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_term_taxonomy.description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.term_taxonomy_id
     *
     * @return the value of cms_term_taxonomy.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.term_taxonomy_id
     *
     * @param termTaxonomyId the value for cms_term_taxonomy.term_taxonomy_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.term_id
     *
     * @return the value of cms_term_taxonomy.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.term_id
     *
     * @param termId the value for cms_term_taxonomy.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.taxonomy
     *
     * @return the value of cms_term_taxonomy.taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getTaxonomy() {
        return taxonomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.taxonomy
     *
     * @param taxonomy the value for cms_term_taxonomy.taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.parent
     *
     * @return the value of cms_term_taxonomy.parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.parent
     *
     * @param parent the value for cms_term_taxonomy.parent
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.count
     *
     * @return the value of cms_term_taxonomy.count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.count
     *
     * @param count the value for cms_term_taxonomy.count
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_term_taxonomy.description
     *
     * @return the value of cms_term_taxonomy.description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_term_taxonomy.description
     *
     * @param description the value for cms_term_taxonomy.description
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}