package cn.coderss.service.user.model;

public class CmsTermmeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_termmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long metaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_termmeta.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_termmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_termmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String metaValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_termmeta.meta_id
     *
     * @return the value of cms_termmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getMetaId() {
        return metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_termmeta.meta_id
     *
     * @param metaId the value for cms_termmeta.meta_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_termmeta.term_id
     *
     * @return the value of cms_termmeta.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_termmeta.term_id
     *
     * @param termId the value for cms_termmeta.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_termmeta.meta_key
     *
     * @return the value of cms_termmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaKey() {
        return metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_termmeta.meta_key
     *
     * @param metaKey the value for cms_termmeta.meta_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_termmeta.meta_value
     *
     * @return the value of cms_termmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getMetaValue() {
        return metaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_termmeta.meta_value
     *
     * @param metaValue the value for cms_termmeta.meta_value
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }
}