package cn.coderss.service.user.model;

public class CmsTerms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_terms.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_terms.name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_terms.slug
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_terms.term_group
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long termGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_terms.term_id
     *
     * @return the value of cms_terms.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_terms.term_id
     *
     * @param termId the value for cms_terms.term_id
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_terms.name
     *
     * @return the value of cms_terms.name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_terms.name
     *
     * @param name the value for cms_terms.name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_terms.slug
     *
     * @return the value of cms_terms.slug
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_terms.slug
     *
     * @param slug the value for cms_terms.slug
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_terms.term_group
     *
     * @return the value of cms_terms.term_group
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getTermGroup() {
        return termGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_terms.term_group
     *
     * @param termGroup the value for cms_terms.term_group
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setTermGroup(Long termGroup) {
        this.termGroup = termGroup;
    }
}