package cn.coderss.service.user.model;

import java.util.Date;

public class CmsUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_login
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_pass
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_nicename
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userNicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_registered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Date userRegistered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_activation_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String userActivationKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.user_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_users.display_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    private String displayName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.ID
     *
     * @return the value of cms_users.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.ID
     *
     * @param id the value for cms_users.ID
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_login
     *
     * @return the value of cms_users.user_login
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_login
     *
     * @param userLogin the value for cms_users.user_login
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_pass
     *
     * @return the value of cms_users.user_pass
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_pass
     *
     * @param userPass the value for cms_users.user_pass
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_nicename
     *
     * @return the value of cms_users.user_nicename
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserNicename() {
        return userNicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_nicename
     *
     * @param userNicename the value for cms_users.user_nicename
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserNicename(String userNicename) {
        this.userNicename = userNicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_email
     *
     * @return the value of cms_users.user_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_email
     *
     * @param userEmail the value for cms_users.user_email
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_url
     *
     * @return the value of cms_users.user_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_url
     *
     * @param userUrl the value for cms_users.user_url
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_registered
     *
     * @return the value of cms_users.user_registered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Date getUserRegistered() {
        return userRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_registered
     *
     * @param userRegistered the value for cms_users.user_registered
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserRegistered(Date userRegistered) {
        this.userRegistered = userRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_activation_key
     *
     * @return the value of cms_users.user_activation_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getUserActivationKey() {
        return userActivationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_activation_key
     *
     * @param userActivationKey the value for cms_users.user_activation_key
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserActivationKey(String userActivationKey) {
        this.userActivationKey = userActivationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.user_status
     *
     * @return the value of cms_users.user_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.user_status
     *
     * @param userStatus the value for cms_users.user_status
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_users.display_name
     *
     * @return the value of cms_users.display_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_users.display_name
     *
     * @param displayName the value for cms_users.display_name
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
}