package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsCommentmeta;
import cn.coderss.service.user.model.CmsCommentmetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsCommentmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsCommentmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsCommentmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsCommentmeta> selectByExampleWithBLOBs(CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsCommentmeta> selectByExample(CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsCommentmeta selectByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsCommentmeta record, @Param("example") CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsCommentmeta record, @Param("example") CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsCommentmeta record, @Param("example") CmsCommentmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsCommentmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsCommentmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_commentmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsCommentmeta record);
}