package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsOptions;
import cn.coderss.service.user.model.CmsOptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsOptions> selectByExampleWithBLOBs(CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsOptions> selectByExample(CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsOptions selectByPrimaryKey(Long optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsOptions record, @Param("example") CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsOptions record, @Param("example") CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsOptions record, @Param("example") CmsOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_options
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsOptions record);
}