package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsPostmeta;
import cn.coderss.service.user.model.CmsPostmetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsPostmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsPostmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsPostmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsPostmeta> selectByExampleWithBLOBs(CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsPostmeta> selectByExample(CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsPostmeta selectByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsPostmeta record, @Param("example") CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsPostmeta record, @Param("example") CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsPostmeta record, @Param("example") CmsPostmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsPostmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsPostmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_postmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsPostmeta record);
}