package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsPosts;
import cn.coderss.service.user.model.CmsPostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsPostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsPosts> selectByExampleWithBLOBs(CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsPosts> selectByExample(CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsPosts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsPosts record, @Param("example") CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsPosts record, @Param("example") CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsPosts record, @Param("example") CmsPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_posts
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsPosts record);
}