package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsTermmeta;
import cn.coderss.service.user.model.CmsTermmetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTermmetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsTermmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsTermmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTermmeta> selectByExampleWithBLOBs(CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTermmeta> selectByExample(CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsTermmeta selectByPrimaryKey(Long metaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsTermmeta record, @Param("example") CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsTermmeta record, @Param("example") CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsTermmeta record, @Param("example") CmsTermmetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsTermmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsTermmeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_termmeta
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsTermmeta record);
}