package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsTermRelationships;
import cn.coderss.service.user.model.CmsTermRelationshipsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTermRelationshipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(@Param("objectId") Long objectId, @Param("termTaxonomyId") Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTermRelationships> selectByExample(CmsTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsTermRelationships selectByPrimaryKey(@Param("objectId") Long objectId, @Param("termTaxonomyId") Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsTermRelationships record, @Param("example") CmsTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsTermRelationships record, @Param("example") CmsTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_relationships
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsTermRelationships record);
}