package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsTermTaxonomy;
import cn.coderss.service.user.model.CmsTermTaxonomyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTermTaxonomyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsTermTaxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsTermTaxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTermTaxonomy> selectByExampleWithBLOBs(CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTermTaxonomy> selectByExample(CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsTermTaxonomy selectByPrimaryKey(Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsTermTaxonomy record, @Param("example") CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CmsTermTaxonomy record, @Param("example") CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsTermTaxonomy record, @Param("example") CmsTermTaxonomyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsTermTaxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CmsTermTaxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_term_taxonomy
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsTermTaxonomy record);
}