package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsTerms;
import cn.coderss.service.user.model.CmsTermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long termId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsTerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsTerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsTerms> selectByExample(CmsTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsTerms selectByPrimaryKey(Long termId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsTerms record, @Param("example") CmsTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsTerms record, @Param("example") CmsTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsTerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_terms
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsTerms record);
}