package cn.coderss.service.user.mapper;

import cn.coderss.service.user.model.CmsUsers;
import cn.coderss.service.user.model.CmsUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int countByExample(CmsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByExample(CmsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insert(CmsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int insertSelective(CmsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    List<CmsUsers> selectByExample(CmsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    CmsUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsUsers record, @Param("example") CmsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByExample(@Param("record") CmsUsers record, @Param("example") CmsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKeySelective(CmsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_users
     *
     * @mbggenerated Thu Nov 02 09:25:49 CST 2017
     */
    int updateByPrimaryKey(CmsUsers record);
}